/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Data requested to the admin when authenticating to the system.
 **/
@ApiModel(description = "Data requested to the admin when authenticating to the system.")
public class AuthenticationDataAdmin {
  
  @SerializedName("mail")
  private String mail = null;
  @SerializedName("password")
  private String password = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMail() {
    return mail;
  }
  public void setMail(String mail) {
    this.mail = mail;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationDataAdmin authenticationDataAdmin = (AuthenticationDataAdmin) o;
    return (this.mail == null ? authenticationDataAdmin.mail == null : this.mail.equals(authenticationDataAdmin.mail)) &&
        (this.password == null ? authenticationDataAdmin.password == null : this.password.equals(authenticationDataAdmin.password));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mail == null ? 0: this.mail.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationDataAdmin {\n");
    
    sb.append("  mail: ").append(mail).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
