/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Generic movement in an organization or in a place of it.
 **/
@ApiModel(description = "Generic movement in an organization or in a place of it.")
public abstract class Movement {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("movementDiscriminator")
  private String movementDiscriminator = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  public enum MovementTypeEnum {
     entrance,  exit, 
  };
  @SerializedName("movementType")
  private MovementTypeEnum movementType = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMovementDiscriminator() {
    return movementDiscriminator;
  }
  public void setMovementDiscriminator(String movementDiscriminator) {
    this.movementDiscriminator = movementDiscriminator;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Type of movement.
   **/
  @ApiModelProperty(required = true, value = "Type of movement.")
  public MovementTypeEnum getMovementType() {
    return movementType;
  }
  public void setMovementType(MovementTypeEnum movementType) {
    this.movementType = movementType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Movement movement = (Movement) o;
    return (this.id == null ? movement.id == null : this.id.equals(movement.id)) &&
        (this.movementDiscriminator == null ? movement.movementDiscriminator == null : this.movementDiscriminator.equals(movement.movementDiscriminator)) &&
        (this.timestamp == null ? movement.timestamp == null : this.timestamp.equals(movement.timestamp)) &&
        (this.movementType == null ? movement.movementType == null : this.movementType.equals(movement.movementType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.movementDiscriminator == null ? 0: this.movementDiscriminator.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.movementType == null ? 0: this.movementType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Movement {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  movementDiscriminator: ").append(movementDiscriminator).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  movementType: ").append(movementType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
