/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Movement to an organization made with the authenticated trackingMode.
 **/
@ApiModel(description = "Movement to an organization made with the authenticated trackingMode.")
public class OrganizationAuthenticatedMovement extends Movement {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("movementDiscriminator")
  private String movementDiscriminator = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("movementType")
  private MovementTypeEnum movementType = null;
  @SerializedName("organizationId")
  private Long organizationId = null;
  @SerializedName("ldapId")
  private Long ldapId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMovementDiscriminator() {
    return movementDiscriminator;
  }
  public void setMovementDiscriminator(String movementDiscriminator) {
    this.movementDiscriminator = movementDiscriminator;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Type of movement.
   **/
  @ApiModelProperty(required = true, value = "Type of movement.")
  public MovementTypeEnum getMovementType() {
    return movementType;
  }
  public void setMovementType(MovementTypeEnum movementType) {
    this.movementType = movementType;
  }

  /**
   * Unique identifier of the organization in which the user had access.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the organization in which the user had access.")
  public Long getOrganizationId() {
    return organizationId;
  }
  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  /**
   * Organization LDAP server's user unique identifier.
   **/
  @ApiModelProperty(required = true, value = "Organization LDAP server's user unique identifier.")
  public Long getLdapId() {
    return ldapId;
  }
  public void setLdapId(Long ldapId) {
    this.ldapId = ldapId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationAuthenticatedMovement organizationAuthenticatedMovement = (OrganizationAuthenticatedMovement) o;
    return (this.id == null ? organizationAuthenticatedMovement.id == null : this.id.equals(organizationAuthenticatedMovement.id)) &&
        (this.movementDiscriminator == null ? organizationAuthenticatedMovement.movementDiscriminator == null : this.movementDiscriminator.equals(organizationAuthenticatedMovement.movementDiscriminator)) &&
        (this.timestamp == null ? organizationAuthenticatedMovement.timestamp == null : this.timestamp.equals(organizationAuthenticatedMovement.timestamp)) &&
        (this.movementType == null ? organizationAuthenticatedMovement.movementType == null : this.movementType.equals(organizationAuthenticatedMovement.movementType)) &&
        (this.organizationId == null ? organizationAuthenticatedMovement.organizationId == null : this.organizationId.equals(organizationAuthenticatedMovement.organizationId)) &&
        (this.ldapId == null ? organizationAuthenticatedMovement.ldapId == null : this.ldapId.equals(organizationAuthenticatedMovement.ldapId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.movementDiscriminator == null ? 0: this.movementDiscriminator.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.movementType == null ? 0: this.movementType.hashCode());
    result = 31 * result + (this.organizationId == null ? 0: this.organizationId.hashCode());
    result = 31 * result + (this.ldapId == null ? 0: this.ldapId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationAuthenticatedMovement {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  movementDiscriminator: ").append(movementDiscriminator).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  movementType: ").append(movementType).append("\n");
    sb.append("  organizationId: ").append(organizationId).append("\n");
    sb.append("  ldapId: ").append(ldapId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
