/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Movement to a place of an organization made with the anonymous trackingMode.
 **/
@ApiModel(description = "Movement to a place of an organization made with the anonymous trackingMode.")
public class PlaceAnonymousMovement extends Movement {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("movementDiscriminator")
  private String movementDiscriminator = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("movementType")
  private MovementTypeEnum movementType = null;
  @SerializedName("placeId")
  private Long placeId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMovementDiscriminator() {
    return movementDiscriminator;
  }
  public void setMovementDiscriminator(String movementDiscriminator) {
    this.movementDiscriminator = movementDiscriminator;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Type of movement.
   **/
  @ApiModelProperty(required = true, value = "Type of movement.")
  public MovementTypeEnum getMovementType() {
    return movementType;
  }
  public void setMovementType(MovementTypeEnum movementType) {
    this.movementType = movementType;
  }

  /**
   * Unique identifier of the place in which the user had access.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the place in which the user had access.")
  public Long getPlaceId() {
    return placeId;
  }
  public void setPlaceId(Long placeId) {
    this.placeId = placeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceAnonymousMovement placeAnonymousMovement = (PlaceAnonymousMovement) o;
    return (this.id == null ? placeAnonymousMovement.id == null : this.id.equals(placeAnonymousMovement.id)) &&
        (this.movementDiscriminator == null ? placeAnonymousMovement.movementDiscriminator == null : this.movementDiscriminator.equals(placeAnonymousMovement.movementDiscriminator)) &&
        (this.timestamp == null ? placeAnonymousMovement.timestamp == null : this.timestamp.equals(placeAnonymousMovement.timestamp)) &&
        (this.movementType == null ? placeAnonymousMovement.movementType == null : this.movementType.equals(placeAnonymousMovement.movementType)) &&
        (this.placeId == null ? placeAnonymousMovement.placeId == null : this.placeId.equals(placeAnonymousMovement.placeId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.movementDiscriminator == null ? 0: this.movementDiscriminator.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.movementType == null ? 0: this.movementType.hashCode());
    result = 31 * result + (this.placeId == null ? 0: this.placeId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceAnonymousMovement {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  movementDiscriminator: ").append(movementDiscriminator).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  movementType: ").append(movementType).append("\n");
    sb.append("  placeId: ").append(placeId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
