/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Access to a place of an organization made with the anonymous trackingMode.
 **/
@ApiModel(description = "Access to a place of an organization made with the anonymous trackingMode.")
public class PlaceAnonymousAccess extends Access {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("accessDiscriminator")
  private String accessDiscriminator = null;
  @SerializedName("entranceTimestamp")
  private Date entranceTimestamp = null;
  @SerializedName("exitTimestamp")
  private Date exitTimestamp = null;
  @SerializedName("placeId")
  private Long placeId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAccessDiscriminator() {
    return accessDiscriminator;
  }
  public void setAccessDiscriminator(String accessDiscriminator) {
    this.accessDiscriminator = accessDiscriminator;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getEntranceTimestamp() {
    return entranceTimestamp;
  }
  public void setEntranceTimestamp(Date entranceTimestamp) {
    this.entranceTimestamp = entranceTimestamp;
  }

  /**
   * Date and time of the moment in which the user left the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user left the place.")
  public Date getExitTimestamp() {
    return exitTimestamp;
  }
  public void setExitTimestamp(Date exitTimestamp) {
    this.exitTimestamp = exitTimestamp;
  }

  /**
   * Unique identifier of the place in which the user had access.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the place in which the user had access.")
  public Long getPlaceId() {
    return placeId;
  }
  public void setPlaceId(Long placeId) {
    this.placeId = placeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceAnonymousAccess placeAnonymousAccess = (PlaceAnonymousAccess) o;
    return (this.id == null ? placeAnonymousAccess.id == null : this.id.equals(placeAnonymousAccess.id)) &&
        (this.accessDiscriminator == null ? placeAnonymousAccess.accessDiscriminator == null : this.accessDiscriminator.equals(placeAnonymousAccess.accessDiscriminator)) &&
        (this.entranceTimestamp == null ? placeAnonymousAccess.entranceTimestamp == null : this.entranceTimestamp.equals(placeAnonymousAccess.entranceTimestamp)) &&
        (this.exitTimestamp == null ? placeAnonymousAccess.exitTimestamp == null : this.exitTimestamp.equals(placeAnonymousAccess.exitTimestamp)) &&
        (this.placeId == null ? placeAnonymousAccess.placeId == null : this.placeId.equals(placeAnonymousAccess.placeId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.accessDiscriminator == null ? 0: this.accessDiscriminator.hashCode());
    result = 31 * result + (this.entranceTimestamp == null ? 0: this.entranceTimestamp.hashCode());
    result = 31 * result + (this.exitTimestamp == null ? 0: this.exitTimestamp.hashCode());
    result = 31 * result + (this.placeId == null ? 0: this.placeId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceAnonymousAccess {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  accessDiscriminator: ").append(accessDiscriminator).append("\n");
    sb.append("  entranceTimestamp: ").append(entranceTimestamp).append("\n");
    sb.append("  exitTimestamp: ").append(exitTimestamp).append("\n");
    sb.append("  placeId: ").append(placeId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
