/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.api;

import it.qbteam.ApiInvoker;
import it.qbteam.ApiException;
import it.qbteam.Pair;

import it.qbteam.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import it.qbteam.model.AdministratorInfo;
import it.qbteam.model.Permission;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class AdministratorApi {
  String basePath = "http://localhost:8080";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Bind an already existent administrator to the organization.
  * Bind an already existent administrator to the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
   * @return Permission
  */
  public Permission bindAdministratorToOrganization (Permission permission) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = permission;
    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling bindAdministratorToOrganization",
        new ApiException(400, "Missing the required parameter 'permission' when calling bindAdministratorToOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/bind";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Permission) ApiInvoker.deserialize(localVarResponse, "", Permission.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Bind an already existent administrator to the organization.
   * Bind an already existent administrator to the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
  */
  public void bindAdministratorToOrganization (Permission permission, final Response.Listener<Permission> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = permission;

    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling bindAdministratorToOrganization",
        new ApiException(400, "Missing the required parameter 'permission' when calling bindAdministratorToOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/bind".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Permission) ApiInvoker.deserialize(localVarResponse,  "", Permission.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Creates and binds a new administrator to the organization.
  * Creates and binds a new administrator to the current organization.  Only web-app administrators can access this end-point.
   * @param administratorInfo 
   * @return Permission
  */
  public Permission createNewAdministratorToOrganization (AdministratorInfo administratorInfo) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = administratorInfo;
    // verify the required parameter 'administratorInfo' is set
    if (administratorInfo == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'administratorInfo' when calling createNewAdministratorToOrganization",
        new ApiException(400, "Missing the required parameter 'administratorInfo' when calling createNewAdministratorToOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/create";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Permission) ApiInvoker.deserialize(localVarResponse, "", Permission.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Creates and binds a new administrator to the organization.
   * Creates and binds a new administrator to the current organization.  Only web-app administrators can access this end-point.
   * @param administratorInfo 
  */
  public void createNewAdministratorToOrganization (AdministratorInfo administratorInfo, final Response.Listener<Permission> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = administratorInfo;

    // verify the required parameter 'administratorInfo' is set
    if (administratorInfo == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'administratorInfo' when calling createNewAdministratorToOrganization",
        new ApiException(400, "Missing the required parameter 'administratorInfo' when calling createNewAdministratorToOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/create".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Permission) ApiInvoker.deserialize(localVarResponse,  "", Permission.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Returns the list of administrators of the organization.
  * Returns the list of administrators of the organization. Only web-app admininistrators can access this end-point.
   * @param organizationId ID of an organization. The administrator must have at least owner permission to the organization.
   * @return List<AdministratorInfo>
  */
  public List<AdministratorInfo> getAdministratorListOfOrganization (Long organizationId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'organizationId' is set
    if (organizationId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'organizationId' when calling getAdministratorListOfOrganization",
        new ApiException(400, "Missing the required parameter 'organizationId' when calling getAdministratorListOfOrganization"));
    }

    // create path and map variables
    String path = "/organization/{organizationId}/administrator".replaceAll("\\{" + "organizationId" + "\\}", apiInvoker.escapeString(organizationId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<AdministratorInfo>) ApiInvoker.deserialize(localVarResponse, "array", AdministratorInfo.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Returns the list of administrators of the organization.
   * Returns the list of administrators of the organization. Only web-app admininistrators can access this end-point.
   * @param organizationId ID of an organization. The administrator must have at least owner permission to the organization.
  */
  public void getAdministratorListOfOrganization (Long organizationId, final Response.Listener<List<AdministratorInfo>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'organizationId' is set
    if (organizationId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'organizationId' when calling getAdministratorListOfOrganization",
        new ApiException(400, "Missing the required parameter 'organizationId' when calling getAdministratorListOfOrganization"));
    }

    // create path and map variables
    String path = "/organization/{organizationId}/administrator".replaceAll("\\{format\\}","json").replaceAll("\\{" + "organizationId" + "\\}", apiInvoker.escapeString(organizationId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<AdministratorInfo>) ApiInvoker.deserialize(localVarResponse,  "array", AdministratorInfo.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Gets the list of permission that an administrator has permissions to view/manage/own.
  * Gets the list of organizations that an administrator has permissions to view/manage/own. Only web-app admininistrators can access this end-point.
   * @param administratorId ID of the administrator. It must be the same of the administratorId of the authenticated administrator.
   * @return List<Permission>
  */
  public List<Permission> getPermissionList (String administratorId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'administratorId' is set
    if (administratorId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'administratorId' when calling getPermissionList",
        new ApiException(400, "Missing the required parameter 'administratorId' when calling getPermissionList"));
    }

    // create path and map variables
    String path = "/organization/permission/{administratorId}".replaceAll("\\{" + "administratorId" + "\\}", apiInvoker.escapeString(administratorId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<Permission>) ApiInvoker.deserialize(localVarResponse, "array", Permission.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Gets the list of permission that an administrator has permissions to view/manage/own.
   * Gets the list of organizations that an administrator has permissions to view/manage/own. Only web-app admininistrators can access this end-point.
   * @param administratorId ID of the administrator. It must be the same of the administratorId of the authenticated administrator.
  */
  public void getPermissionList (String administratorId, final Response.Listener<List<Permission>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'administratorId' is set
    if (administratorId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'administratorId' when calling getPermissionList",
        new ApiException(400, "Missing the required parameter 'administratorId' when calling getPermissionList"));
    }

    // create path and map variables
    String path = "/organization/permission/{administratorId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "administratorId" + "\\}", apiInvoker.escapeString(administratorId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<Permission>) ApiInvoker.deserialize(localVarResponse,  "array", Permission.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Unbind an administrator to the organization.
  * Unbind an administrator to the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
   * @return void
  */
  public void unbindAdministratorFromOrganization (Permission permission) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = permission;
    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling unbindAdministratorFromOrganization",
        new ApiException(400, "Missing the required parameter 'permission' when calling unbindAdministratorFromOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/unbind";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return ;
      } else {
         return ;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Unbind an administrator to the organization.
   * Unbind an administrator to the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
  */
  public void unbindAdministratorFromOrganization (Permission permission, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = permission;

    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling unbindAdministratorFromOrganization",
        new ApiException(400, "Missing the required parameter 'permission' when calling unbindAdministratorFromOrganization"));
    }

    // create path and map variables
    String path = "/organization/administrator/unbind".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
              responseListener.onResponse(localVarResponse);
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Update the permission for an already existent administrator in the organization.
  * Update the permission for an already existent administrator in the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
   * @return Permission
  */
  public Permission updateAdministratorPermission (Permission permission) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = permission;
    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling updateAdministratorPermission",
        new ApiException(400, "Missing the required parameter 'permission' when calling updateAdministratorPermission"));
    }

    // create path and map variables
    String path = "/organization/administrator/update";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (Permission) ApiInvoker.deserialize(localVarResponse, "", Permission.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Update the permission for an already existent administrator in the organization.
   * Update the permission for an already existent administrator in the organization. Only web-app admininistrators can access this end-point.
   * @param permission 
  */
  public void updateAdministratorPermission (Permission permission, final Response.Listener<Permission> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = permission;

    // verify the required parameter 'permission' is set
    if (permission == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'permission' when calling updateAdministratorPermission",
        new ApiException(400, "Missing the required parameter 'permission' when calling updateAdministratorPermission"));
    }

    // create path and map variables
    String path = "/organization/administrator/update".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((Permission) ApiInvoker.deserialize(localVarResponse,  "", Permission.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
