/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import it.qbteam.model.Administrator;
import it.qbteam.model.Permission;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AdministratorInfo {
  
  @SerializedName("mail")
  private String mail = null;
  @SerializedName("admininistrator")
  private Administrator admininistrator = null;
  @SerializedName("permission")
  private Permission permission = null;

  /**
   * Mail of the administrator.
   **/
  @ApiModelProperty(required = true, value = "Mail of the administrator.")
  public String getMail() {
    return mail;
  }
  public void setMail(String mail) {
    this.mail = mail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Administrator getAdmininistrator() {
    return admininistrator;
  }
  public void setAdmininistrator(Administrator admininistrator) {
    this.admininistrator = admininistrator;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Permission getPermission() {
    return permission;
  }
  public void setPermission(Permission permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdministratorInfo administratorInfo = (AdministratorInfo) o;
    return (this.mail == null ? administratorInfo.mail == null : this.mail.equals(administratorInfo.mail)) &&
        (this.admininistrator == null ? administratorInfo.admininistrator == null : this.admininistrator.equals(administratorInfo.admininistrator)) &&
        (this.permission == null ? administratorInfo.permission == null : this.permission.equals(administratorInfo.permission));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mail == null ? 0: this.mail.hashCode());
    result = 31 * result + (this.admininistrator == null ? 0: this.admininistrator.hashCode());
    result = 31 * result + (this.permission == null ? 0: this.permission.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdministratorInfo {\n");
    
    sb.append("  mail: ").append(mail).append("\n");
    sb.append("  admininistrator: ").append(admininistrator).append("\n");
    sb.append("  permission: ").append(permission).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
