/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Movement in an organization.
 **/
@ApiModel(description = "Movement in an organization.")
public class OrganizationMovement {
  
  @SerializedName("exitToken")
  private String exitToken = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("movementType")
  private Integer movementType = null;
  @SerializedName("organizationId")
  private Long organizationId = null;
  @SerializedName("orgAuthServerId")
  private String orgAuthServerId = null;

  /**
   * Token generated by the server when the user entered in the organization. It is required only to track an exit movement. If this property is not empty in an entrance movement it will not be considered.
   **/
  @ApiModelProperty(value = "Token generated by the server when the user entered in the organization. It is required only to track an exit movement. If this property is not empty in an entrance movement it will not be considered.")
  public String getExitToken() {
    return exitToken;
  }
  public void setExitToken(String exitToken) {
    this.exitToken = exitToken;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Type of movement. It can be: - Entrance: 1 - Exit: -1
   **/
  @ApiModelProperty(required = true, value = "Type of movement. It can be: - Entrance: 1 - Exit: -1")
  public Integer getMovementType() {
    return movementType;
  }
  public void setMovementType(Integer movementType) {
    this.movementType = movementType;
  }

  /**
   * Unique identifier of the organization in which the user had access.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the organization in which the user had access.")
  public Long getOrganizationId() {
    return organizationId;
  }
  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  /**
   * User unique identifier from the authentication server of the organization.
   **/
  @ApiModelProperty(value = "User unique identifier from the authentication server of the organization.")
  public String getOrgAuthServerId() {
    return orgAuthServerId;
  }
  public void setOrgAuthServerId(String orgAuthServerId) {
    this.orgAuthServerId = orgAuthServerId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationMovement organizationMovement = (OrganizationMovement) o;
    return (this.exitToken == null ? organizationMovement.exitToken == null : this.exitToken.equals(organizationMovement.exitToken)) &&
        (this.timestamp == null ? organizationMovement.timestamp == null : this.timestamp.equals(organizationMovement.timestamp)) &&
        (this.movementType == null ? organizationMovement.movementType == null : this.movementType.equals(organizationMovement.movementType)) &&
        (this.organizationId == null ? organizationMovement.organizationId == null : this.organizationId.equals(organizationMovement.organizationId)) &&
        (this.orgAuthServerId == null ? organizationMovement.orgAuthServerId == null : this.orgAuthServerId.equals(organizationMovement.orgAuthServerId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.exitToken == null ? 0: this.exitToken.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.movementType == null ? 0: this.movementType.hashCode());
    result = 31 * result + (this.organizationId == null ? 0: this.organizationId.hashCode());
    result = 31 * result + (this.orgAuthServerId == null ? 0: this.orgAuthServerId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationMovement {\n");
    
    sb.append("  exitToken: ").append(exitToken).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  movementType: ").append(movementType).append("\n");
    sb.append("  organizationId: ").append(organizationId).append("\n");
    sb.append("  orgAuthServerId: ").append(orgAuthServerId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
