/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Number of people currently inside the organization&#39;s trackingArea.
 **/
@ApiModel(description = "Number of people currently inside the organization's trackingArea.")
public class OrganizationPresenceCounter {
  
  @SerializedName("organizationId")
  private Long organizationId = null;
  @SerializedName("counter")
  private Integer counter = null;

  /**
   * Unique identifier of the organization.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the organization.")
  public Long getOrganizationId() {
    return organizationId;
  }
  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  /**
   * Number of people currently inside the organization's trackingArea.
   **/
  @ApiModelProperty(required = true, value = "Number of people currently inside the organization's trackingArea.")
  public Integer getCounter() {
    return counter;
  }
  public void setCounter(Integer counter) {
    this.counter = counter;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationPresenceCounter organizationPresenceCounter = (OrganizationPresenceCounter) o;
    return (this.organizationId == null ? organizationPresenceCounter.organizationId == null : this.organizationId.equals(organizationPresenceCounter.organizationId)) &&
        (this.counter == null ? organizationPresenceCounter.counter == null : this.counter.equals(organizationPresenceCounter.counter));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.organizationId == null ? 0: this.organizationId.hashCode());
    result = 31 * result + (this.counter == null ? 0: this.counter.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationPresenceCounter {\n");
    
    sb.append("  organizationId: ").append(organizationId).append("\n");
    sb.append("  counter: ").append(counter).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
