/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.qbteam.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Movement in a place of an organization.
 **/
@ApiModel(description = "Movement in a place of an organization.")
public class PlaceMovement {
  
  @SerializedName("exitToken")
  private String exitToken = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("movementType")
  private Integer movementType = null;
  @SerializedName("placeId")
  private Long placeId = null;
  @SerializedName("orgAuthServerId")
  private String orgAuthServerId = null;

  /**
   * Token generated by the server when the user entered in the organization. It is required only to track an exit movement. If this property is not empty in an entrance movement it will not be considered.
   **/
  @ApiModelProperty(value = "Token generated by the server when the user entered in the organization. It is required only to track an exit movement. If this property is not empty in an entrance movement it will not be considered.")
  public String getExitToken() {
    return exitToken;
  }
  public void setExitToken(String exitToken) {
    this.exitToken = exitToken;
  }

  /**
   * Date and time of the moment in which the user entered the place.
   **/
  @ApiModelProperty(required = true, value = "Date and time of the moment in which the user entered the place.")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Type of movement. It can be: - Entrance: 1 - Exit: -1
   **/
  @ApiModelProperty(required = true, value = "Type of movement. It can be: - Entrance: 1 - Exit: -1")
  public Integer getMovementType() {
    return movementType;
  }
  public void setMovementType(Integer movementType) {
    this.movementType = movementType;
  }

  /**
   * Unique identifier of the place in which the user had access.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier of the place in which the user had access.")
  public Long getPlaceId() {
    return placeId;
  }
  public void setPlaceId(Long placeId) {
    this.placeId = placeId;
  }

  /**
   * User unique identifier from the authentication server of the organization.
   **/
  @ApiModelProperty(value = "User unique identifier from the authentication server of the organization.")
  public String getOrgAuthServerId() {
    return orgAuthServerId;
  }
  public void setOrgAuthServerId(String orgAuthServerId) {
    this.orgAuthServerId = orgAuthServerId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceMovement placeMovement = (PlaceMovement) o;
    return (this.exitToken == null ? placeMovement.exitToken == null : this.exitToken.equals(placeMovement.exitToken)) &&
        (this.timestamp == null ? placeMovement.timestamp == null : this.timestamp.equals(placeMovement.timestamp)) &&
        (this.movementType == null ? placeMovement.movementType == null : this.movementType.equals(placeMovement.movementType)) &&
        (this.placeId == null ? placeMovement.placeId == null : this.placeId.equals(placeMovement.placeId)) &&
        (this.orgAuthServerId == null ? placeMovement.orgAuthServerId == null : this.orgAuthServerId.equals(placeMovement.orgAuthServerId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.exitToken == null ? 0: this.exitToken.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.movementType == null ? 0: this.movementType.hashCode());
    result = 31 * result + (this.placeId == null ? 0: this.placeId.hashCode());
    result = 31 * result + (this.orgAuthServerId == null ? 0: this.orgAuthServerId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceMovement {\n");
    
    sb.append("  exitToken: ").append(exitToken).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  movementType: ").append(movementType).append("\n");
    sb.append("  placeId: ").append(placeId).append("\n");
    sb.append("  orgAuthServerId: ").append(orgAuthServerId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
